name: NanoPi-R2s OpenWrt + Lean

on:
  push:
    branches: 
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master

      - name: 初始化环境
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
          sudo -E apt-get update
          sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git \
                                     libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 \
                                     libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib \
                                     p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto \
                                     qemu-utils upx libelf-dev autoconf automake libtool autopoint \
                                     device-tree-compiler
          wget -O - https://raw.githubusercontent.com/friendlyarm/build-env-on-ubuntu-bionic/master/install.sh | bash   
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
          git clone https://github.com/friendlyarm/repo
          sudo cp repo/repo /usr/bin/
          sudo chmod 755 /usr/bin/repo
          
      - name: 下载 friendlywrt-rk3328 并 merge lean lede
        run: |
          mkdir friendlywrt-rk3328
          cd friendlywrt-rk3328
          repo init -u https://github.com/friendlyarm/friendlywrt_manifests -b master -m rk3328.xml --repo-url=https://github.com/friendlyarm/repo  --no-clone-bundle
          repo sync -c  --no-clone-bundle
          git clone https://github.com/coolsnowwolf/lede
          cd friendlywrt
          cp -r ../lede/package/lean package/
          sed -i 's/https:\/\/github.com\/friendlyarm\/friendlywrt_project_luci^bb021b4b9097ad332ab40bce2a1c239d9fcf225b/https:\/\/github.com\/coolsnowwolf\/luci/' feeds.conf.default
          sed -i 's/https:\/\/git.openwrt.org\/feed\/packages.git^54266c99b2a2e37a4c01b02ae74346874db7003c/https:\/\/github.com\/coolsnowwolf\/packages/' feeds.conf.default          
          
      - name: Update Target.mk
        run: |
          cd friendlywrt-rk3328/friendlywrt/include 
          sed -i 's/dnsmasq /dnsmasq-full default-settings luci /' target.mk    
          
      - name: Update Feeds
        run: |
          cd friendlywrt-rk3328/friendlywrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          
      - name: Costom Configure File
        run: |
          cd friendlywrt-rk3328/friendlywrt
          rm -f ./.config*
          wget https://raw.githubusercontent.com/anyUesr/lede_r2s/master/config.txt
          cp config.txt .config
          wget https://raw.githubusercontent.com/anyUesr/lede_r2s/master/default.txt
          cp default.txt package/lean/default-settings/files/zzz-default-settings
          make defconfig
      
      - name: Download package
        if: always()
        run: |
          cd friendlywrt-rk3328/friendlywrt
          make download -j32
          find dl -size -1024c -exec ls -l {} \;
          find dl -size -1024c -exec rm -f {} \;
          
      - name: Build OpenWrt
        run: |
          cd friendlywrt-rk3328
          bash -x build.sh nanopi_r2s.mk
      
      - name: Zip Files
        run: |
          find friendlywrt-rk3328/out/ -name "FriendlyWrt_*img*" | xargs -i zip -r {}.zip {}
          
      - name: Assemble Artifact
        run: |
          rm -rf ./artifact/
          mkdir -p ./artifact/
          find friendlywrt-rk3328/out/ -name "FriendlyWrt_*img.zip*" | xargs -i mv -f {} ./artifact/
      - name: Upload Artifact
        uses: actions/upload-artifact@master
        with:
          name: FriendlyWrt_NanoPi-R2S
          path: ./artifact/
